#!/bin/sh

if [ -z "${SERVITOR_HOME}" ]
then
  echo "SERVITOR_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${SERVITOR_HOME}/lib" \
-m com.io7m.servitor.cmdline/com.io7m.servitor.cmdline.SvMain \
"$@"
